cacheSpec: maximumSize=10000, expireAfterAccess=1h

logging:
  level: INFO
  loggers:
    com.alexkudlick.authentication: DEBUG
    io.dropwizard: INFO
  appenders:
    - type: console

database:
  driverClass: com.mysql.jdbc.Driver
  url: ${DATABASE_JDBC_URL}
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.MySQLDialect
  maxWaitForConnection: 1s
  validationQuery: "/* MyApplication Health Check */ SELECT 1"
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: true
  checkConnectionOnBorrow: true
